services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql-teste07
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: teste07
      MYSQL_USER: teste07
      MYSQL_PASSWORD: 123
    ports:
      - "3308:3306"
    volumes:
      - mysql-teste07:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-teste07
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123
      PMA_USER: teste07
      PMA_PASSWORD: 123
    ports:
      - "8087:80"

volumes:
  mysql-teste07: